---
ID: "76045785-d1a7-49d5-a261-3fbd4bccb8b0"
Parent: "75f10319-36a5-400a-a524-1a9a91a649cc"
Template: "75f10319-36a5-400a-a524-1a9a91a649cc"
Path: /sitecore/templates/Nintendo/Tables/TableRaw/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180605T181425Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
